### ISSUE TITLE
error enabling dangerous caves 2

### ISSUE THREAD

**Issue by frogglen** [imDaniX/Dangerous-Caves-2#19]
```
.... [17:28:51 ERROR]: Error occurred while enabling DangerousCaves v2.2.2;16 (Is it up to date?)

java.lang.NullPointerException: null
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.15.2.jar:git-Tuinity-"d8b8905"]
at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:100) ~[?:?]
at me.imdanix.caves.regions.WorldGuard7Manager.onEnable(WorldGuard7Manager.java:63) ~[?:?]
at java.util.HashMap$Values.forEach(HashMap.java:976) ~[?:?]
at me.imdanix.caves.regions.Regions.onEnable(Regions.java:72) ~[?:?]
at me.imdanix.caves.DangerousCaves.onEnable(DangerousCaves.java:63) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Tuinity-"d8b8905"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Tuinity-"d8b8905"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Tuinity-"d8b8905"]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Tuinity-"d8b8905"]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Tuinity-"d8b8905"]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Tuinity-"d8b8905"]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Tuinity-"d8b8905"]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.15.2.jar:git-Tuinity-"d8b8905"]
at java.lang.Thread.run(Thread.java:834) [?:?]
.... [17:28:51 INFO]: [DangerousCaves] Disabling DangerousCaves v2.2.2;16
```

Server: Tuinity Build #106
Plugin: Dangerous caves versión: 2.2.2

**Comment by imDaniX** [comment]
Do you have WorldGuard installed?

**Comment by frogglen** [comment]
> Do you have WorldGuard installed?

yes, i have worldguard installed, this error happens when i try to install some plugin on my server such as: WorldGuardExtraFlags

But it also happened to me when I try to install another plugin like: PVPManager

I have never had this problem before.

**Comment by frogglen** [comment]
> Do you have WorldGuard installed?

> Plugins (47): AnimatedScoreboard, antiRedstoneClock, BloodMoon, ChatControl, CMI, CMIPaperLib, CommandCooldown*, CoreLibs, CoreProtect, DangerousCaves, DiscordSRV, DragonEggDrop, Duels, ExtraHardMode, FastCraft, Graves, IllegalStack, InventoryRollback, LastLoginAPI, LimitPillagers, LuckPerms, MaintenanceSpigot, Matrix, Multiverse-Core, MyPet, nLogin, Oh_the_dungeons_youll_go, Parties, PerWorldInventory, PlaceholderAPI, PlayerKits, ProtectionStones, ProtocolLib, RecipeManager, ServerBooster, ServerlistMOTD*, Shopkeepers, SkinsRestorer, SmoothSleep, TAB, TabCompleteFilter, TradeSystem, UltimateTimber, Vault, VillagerOptimiser, WorldEdit, WorldGuard

**Comment by imDaniX** [comment]
And you don't use /reload command, yeah?

**Comment by frogglen** [comment]
> And you don't use /reload command, yeah?

I have not tried using the reload command

**Comment by imDaniX** [comment]
Good. Thank you for the report.

**Comment by imDaniX** [comment]
Please try latest build.

**Comment by frogglen** [comment]
> Please try latest build.

Thank you very much, when I have time to try it, I will let you know around here.

**Comment by frogglen** [comment]
> Please try latest build.

the error is already solved, try to install the wordguardextraflags plugin and the pvpmanager again and everything worked perfectly, it no longer gives an error when starting.

Thanks

**Comment by imDaniX** [comment]
That's good. Will close the issue then.
