### ISSUE TITLE
Error while starting server

### ISSUE THREAD

**Issue by Nqndi** [imDaniX/Dangerous-Caves-2#34]
**Describe the bug**
So, when I start my 1.12.2 spigot server, I get an error in the console saying it couldn't load the plugin since an error occurred.

**Screenshots or logs**
`[15:03:07 INFO]: [DangerousCaves] Enabling DangerousCaves v2.2.11;22
[15:03:07 ERROR]: Error occurred while enabling DangerousCaves v2.2.11;22 (Is it up to date?)
java.lang.NoSuchFieldError: RAIL
        at me.imdanix.caves.util.Materials.<clinit>(Materials.java:67) ~[?:?]
        at me.imdanix.caves.mobs.defaults.MagmaMonster.<clinit>(MagmaMonster.java:55) ~[?:?]
        at me.imdanix.caves.DefaultMobs.<clinit>(DefaultMobs.java:41) ~[?:?]
        at me.imdanix.caves.DangerousCaves.onEnable(DangerousCaves.java:63) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]`

**Additional information**
- 1.12.2
- Dangerous-caves-2.2.11.jar
- Spigot
- Dangerous-caves, dangerousNether, EpicWorldGenerator, Multiverse.
-EpicWorldGenerator works with GiantCaves plugin, so it shouldn't be a problem.

**Comment by imDaniX** [comment]
Should be fixed now, try latest build.
