### ISSUE TITLE
Error in console when builded

### ISSUE THREAD

**Issue by Kavaliunus** [imDaniX/Dangerous-Caves-2#38]
[20:51:25 ERROR]: Error occurred while enabling DangerousCaves v2.2.12-SNAPSHOT;22 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at me.imdanix.caves.DangerousCaves.onEnable(DangerousCaves.java:99) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-240]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-240]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-240]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-240]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-240]        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-240]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
        at org.bstats.bukkit.MetricsLite.<clinit>(MetricsLite.java:43) ~[?:?]
        ... 11 more

**Comment by imDaniX** [comment]
Are you doing it correctly? Seems like you somehow skipped relocation part.
```
git clone https://github.com/imDaniX/Dangerous-Caves-2.git
cd ./Dangerous-Caves-2
mvn clean package
```
Resulting package is Dangerous-Caves-2/Dangerous-Caves/target/Dangerous-Caves-2.2.12-SNAPSHOT.jar
